tasks:
  - name: Spring Boot (Gradle)
    init: |
    command: |
      bash .gitpod/init-spring.sh
  - name: MySQL Setup
    init: |
    command: |
      bash .gitpod/init-db.sh
  - name: React & TypeScript
    init: |
      cd shop/frontend
      npm install --legacy-peer-deps
    command: |
      cd shop/frontend
      npm start
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: public
  - port: 8080
    onOpen: ignore
    visibility: public
