tasks:
  - name: React & TypeScript
    init: |
      cd frontend
      npm install --legacy-peer-deps
    command: |
      cd frontend
      npm start
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public