tasks:
  - name: MySQL Setup
    init: |
      bash .gitpod/init-db.sh
  - name: React & TypeScript
    init: |
      cd frontend
      npm install --legacy-peer-deps
    command: |
      cd frontend
      npm start

ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3306
    onOpen: open-preview
    visibility: public
